server:
  port: 8888
spring:
  application:
    name: reto-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rubenmt99/reto-config-service.git
        default-label: master
        search-paths:
        - '*service*'

